name: Azure VM On/Off Workflow

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write  
  contents: write
  actions: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    
    - name: 'Login to Azure'
      uses: azure/login@v1  
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    
    - name: 'Start Azure VM and get details'
      run: |
        az vm start --resource-group auto_vm_on_off_central_us --name action-vm-on-off-central-us
        echo "VM started"
        
        # Get VM  IP
        
        VM_IP=$(az vm show --resource-group auto_vm_on_off_central_us --name $VM_NAME --show-details --query publicIps -o tsv)
        
        # Print VM  IP
        
        echo "VM Public IP: $VM_IP"

    
    - name: 'Always stop Azure VM'
      if: always()
      run: |
        az vm deallocate --resource-group auto_vm_on_off_central_us --name action-vm-on-off-central-us

        echo "VM stoped"
