# name: Azure VM On/Off Workflow

# on: 
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# permissions:
#   id-token: write
#   actions: write
#   contents: write

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest

#     steps:
#     # Step 1: Log in to Azure using the Service Principal
#     - name: 'Login to Azure'
#       uses: azure/login@v1
#       with:
#         client-id: ${{ secrets.AZURE_CLIENT_ID }}
#         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#         client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

#     # Step 2: Start the Azure VM (turn it on)
#     - name: 'Start Azure VM'
#       run: |
#         az vm start --resource-group auto_vm_on_off_central_us --name action-vm-on-off-central-us

#     # Step 3: Check out the code
#     - name: 'Check out code'
#       uses: actions/checkout@v2

#     # Step 4: (Optional) Install Dependencies (Python example)
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip

#     # Step 5: (Optional) Run your tests/build
#     - name: Run tests
#       run: |
#         pytest

#     # Step 6: Always stop the Azure VM (turn it off)
#     - name: 'Always stop Azure VM'
#       if: always()
#       run: |
#         az vm deallocate --resource-group auto_vm_on_off_central_us --name action-vm-on-off-central-us


name: Azure VM On/Off Workflow

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write  # Required for OIDC authentication
  contents: write
  actions: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Log in to Azure using OIDC
    - name: 'Login to Azure using OIDC'
      uses: azure/login@v1.6.3
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}  # Your client ID
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}  # Your tenant ID
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # Your subscription ID
        auth-type: 'oidc'  # Use OIDC authentication

    # Step 2: Start the Azure VM (turn it on)
    - name: 'Start Azure VM'
      run: |
        az vm start --resource-group auto_vm_on_off_central_us --name action-vm-on-off-central-us

    # Step 3: Check out the code
    - name: 'Check out code'
      uses: actions/checkout@v2

    # Step 4: (Optional) Install Dependencies (Python example)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    # Step 5: (Optional) Run your tests/build
    - name: Run tests
      run: |
        pytest

    # Step 6: Always stop the Azure VM (turn it off)
    - name: 'Always stop Azure VM'
      if: always()  
      run: |
        az vm deallocate --resource-group auto_vm_on_off_central_us --name action-vm-on-off-central-us
